"""Alert domain model."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any
from uuid import uuid4


class AlertType(str, Enum):
    CONVICTION_CHANGE = "conviction_change"
    PRICE_TRIGGER = "price_trigger"
    NEW_EVIDENCE = "new_evidence"
    THESIS_INVALIDATED = "thesis_invalidated"
    THESIS_EXPIRY = "thesis_expiry"
    PREMISE_INVALIDATION = "premise_invalidation"
    PORTFOLIO_RISK = "portfolio_risk"
    MODEL_DRIFT = "model_drift"


@dataclass
class Alert:
    """An alert generated by the scan system."""

    symbol: str
    alert_type: AlertType
    message: str
    data: dict[str, Any] = field(default_factory=dict)
    read: bool = False
    id: str = field(default_factory=lambda: str(uuid4())[:8])
    created_at: datetime = field(default_factory=datetime.now)
